language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev

before_install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  -

script:
  - python tests.py
